# Generated by Django 4.2.29 on 2026-03-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
    ]
