# Generated by Django 6.0.3 on 2026-03-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0003_repository_project_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='path',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='path',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='versionfile',
            name='path',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
