# Generated by Django 6.0.3 on 2026-03-30 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0004_project_path_projectversion_path_repository_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='project_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcs_core.projectversion'),
        ),
    ]
