# Generated by Django 6.0.3 on 2026-03-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0005_auditlog_project_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versionfile',
            options={'verbose_name': 'Version File'},
        ),
        migrations.AlterUniqueTogether(
            name='versionfile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='versionfile',
            name='versions',
            field=models.ManyToManyField(related_name='version_files', to='vcs_core.projectversion'),
        ),
        migrations.RemoveField(
            model_name='versionfile',
            name='version',
        ),
    ]
