# Generated by Django 6.0.3 on 2026-03-30 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0006_alter_versionfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_role', models.CharField(choices=[('Author', 'Author'), ('Reviewer', 'Reviewer'), ('Reader', 'Reader'), ('Admin', 'Admin')], default='Reader', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs_core.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs_core.user')),
            ],
            options={
                'unique_together': {('user', 'repository')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='repositories',
            field=models.ManyToManyField(related_name='members', through='vcs_core.RepositoryMembership', to='vcs_core.repository'),
        ),
    ]
