# Generated by Django 6.0.3 on 2026-03-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0007_repositorymembership_user_repositories'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='repository',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
