# Generated by Django 6.0.3 on 2026-03-31 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0009_alter_auditlog_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcs_core.repository'),
        ),
    ]
