# Generated by Django 6.0.3 on 2026-04-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0010_alter_auditlog_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repoType',
            field=models.CharField(default='Studio', max_length=255),
        ),
    ]
