# Generated by Django 6.0.3 on 2026-04-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs_core', '0011_repository_repotype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersionComment',
        ),
    ]
