from django.urls import path
from . import views

urlpatterns = [
    path('logs/user/<int:inputUserID>/', views.getUserAuditLogs_View),
    path('logs/project/<int:inputProjectID>/', views.getProjectAuditLogs_View),
    path('projects/<int:inputProjectID>/', views.getProjectByID_View),
    path('projects/user/<int:user_id>', views.getUserProjects_View),
    path('logs/version/<int:inputProjectVersionID>/', views.getProjectVersionAuditLogsByID_View),
    path('projects/<int:inputProjectId>/versions/', views.getProjectVersionsByProjectID_View),
    path('versions/by-file/<int:version_file_id>/', views.getProjectVersionSpecificByVersionFile_View),
    path('projects/<int:inputProjectId>/files/', views.getAllProjectFilesByProjectID_View),
    path('versions/<int:inputVersionID>/files/', views.getProjectVersionFilesByProjectVersionID_View),
    path('users/get-or-create/', views.getOrCreateUser_View),
    path('logs/create-project/', views.logCreateProject_View),
    path('projects/add/', views.addProjectToDB_View),
    path('versions/add-next/', views.addNextProjectVersion_View),
    path('files/add-to-version/', views.addVersionFileToDB_View),
    path('files/remove-from-version/', views.removeVersionFileFromDB_View),
    path('code-files/<int:project_id>/delete/', views.removeCodeFileFromDB_View),
    path('projects/<int:project_id>/delete/', views.removeProjectFromDB_View),
    path('users/<int:user_id>/repos/', views.getUserRepos_View),
    path('repos/<int:repo_id>/projects/', views.getRepoProjectsByRepo_View),
    path('repos/<int:repo_id>/logs/', views.getRepoAuditLogsByRepo_View),
    path('repos/name/<str:repo_name>/logs/', views.getRepoAuditLogsByRepoName_View),
    path('repos/name/<str:inputRepoName>', views.getRepoByName_View),
    path('files/<int:inputVersionFileID>/versions-summary/', views.getVersionsByFileID_View),
    path('utility/get-path/', views.getElementRelativePath_View),
    path('projects/<int:project_id>/latest-version/', views.getLatestProjectVersion_View),
    path('files/by-path/', views.getVersionFileByPath_View),
    path('files/check-link/', views.isFileLinkedToVersion_View),
    path('files/link-to-version/', views.linkExistingFileToVersion_View),
    path('versions/<int:version_id>/delete/', views.removeProjectVersionFromDB_View),
    path('projects/create-with-initial/', views.addProjectAndInitialVersionToDB_View),
    path('projects/check-path/', views.checkAbsPathToCodeFile_View),
    path('projects/versions/upload-code/', views.addNextCodeFileVersion_View),
    path('projects/initialize-code-file/', views.addInitialCodeFileToDB_View),
    path('repositories/create/', views.createRepositoryInDB_View),
    path('repositories/<int:repo_id>/delete/', views.removeRepositoryFromDB_View),

]